#!/usr/bin/env python3
"""Generate FILE_INVENTORY.md for the DataForge Scraper repository."""

import os
import subprocess

REPO = "/home/harshit/Documents/Work/Money/scraper"
OUT = os.path.join(REPO, "artifacts", "audit", "FILE_INVENTORY.md")


def classify(rel):
    parts = rel.split(os.sep)
    filename = os.path.basename(rel)

    # --- Generated / cache / vendor ---
    if "__pycache__" in parts:
        return "generated", "Python bytecode", "No", "Generated bytecode cache"
    if "playwright-report" in parts:
        return "generated", "Test report", "No", "Generated by Playwright"
    if "artifacts" in parts and "validation" in parts:
        return "generated", "Validation/CI artifact", "No", "CI validation log"
    if "dist" in parts and rel.startswith("frontend/"):
        return "generated", "Build output", "No", "Generated frontend build"
    if ".venv" in parts:
        return "vendor", "Python dependencies", "No", "Virtual environment"
    if "node_modules" in parts:
        return "vendor", "NPM packages", "No", "Node.js dependencies"
    if ".pytest_cache" in parts:
        return "cache", "pytest cache", "No", "Test framework cache"
    if ".mypy_cache" in parts:
        return "cache", "mypy cache", "No", "Type analysis cache"
    if ".ruff_cache" in parts:
        return "cache", "ruff cache", "No", "Linting tool cache"
    if any(p in parts for p in [".coverage"]):
        return "generated", "Generated/cache", "No", "Generated/cache artifact"

    # --- Backend source (Python only) ---
    if (rel.startswith("backend/app/") or rel.startswith("backend/forge_kernel/")) and filename.endswith(".py"):
        return "backend_source", "Python backend source", "Yes", ""

    # --- Tests ---
    if rel.startswith("backend/tests/") and filename.endswith(".py"):
        return "test", "Test suite", "Yes", ""
    if rel.startswith("backend/benchmarks/") and filename.endswith(".py"):
        return "test", "Benchmark tests", "No", ""

    # --- Scripts ---
    if rel.startswith("scripts/"):
        return "script", "Dev/ops scripts", "Yes", ""

    # --- Frontend source ---
    if rel.startswith("frontend/"):
        if filename.endswith((".html", ".css", ".js", ".mjs")):
            return "frontend_source", "Frontend source code", "Yes", ""
        if filename.endswith(".svg"):
            return "asset", "Icon/web asset", "No", ""
        if filename in ("playwright.config.mjs", "vitest.config.js"):
            return "config", "Frontend tooling config", "No", ""
        return "frontend_source", "Frontend file", "Yes", ""

    # --- Documentation ---
    if rel.startswith("docs/"):
        return "documentation", "Documentation", "No", ""
    if filename in (
        "README.md",
        "CHANGELOG.md",
        "CODE_REVIEW_BUGS.md",
        "LICENSE",
        "THIRD_PARTY_NOTICES.md",
        "AGENTS.md",
        "PROJECT_STATUS.md",
    ):
        return "documentation", "Project documentation", "No", ""
    if "Instructions_for_ai" in parts:
        return "documentation", "AI instructions", "No", ""

    # --- Config ---
    if filename.startswith(".env"):
        return "config", "Environment configuration", "No", ""
    if filename in (
        "pyproject.toml",
        "package.json",
        "package-lock.json",
        "uv.lock",
        ".pre-commit-config.yaml",
        ".prettierrc",
        ".prettierignore",
        ".stylelintrc.json",
        ".gitignore",
        "Makefile",
        ".dockerignore",
    ):
        return "config", "Project/tooling config", "No", ""

    # --- Docker / Deployment ---
    if filename.startswith("docker-compose") or filename in (
        "Dockerfile",
        "nginx.conf",
        "prometheus.yml",
        "prometheus_web.yml",
        "prometheus_alerts.yml",
        "alertmanager.yml",
    ):
        return "docker/deployment", "Deployment & ops", "No", ""
    if rel.startswith("grafana/"):
        return "docker/deployment", "Deployment & ops", "No", ""

    # --- Binary / data ---
    if filename.endswith((".sqlite", ".db")):
        return "binary", "Database file", "No", ""
    if (rel.startswith("backend/data/") or rel.startswith("data/")) and any(
        filename.endswith(ext) for ext in (".json", ".jsonl", ".lock")
    ):
        return "binary", "Data/storage file", "No", ""

    # --- Logs ---
    if rel.startswith("logs/"):
        return "generated", "Log file", "No", "Application log"

    return "unknown", "Unclassified", "No", ""


def main():
    result = subprocess.run(
        ["find", REPO, "-type", "f"], capture_output=True, text=True
    )
    all_paths = sorted(result.stdout.strip().split("\n"))
    rows = []
    for path in all_paths:
        if not path:
            continue
        rel = os.path.relpath(path, REPO)
        ft, purpose, is_source, skip_reason = classify(rel)
        rows.append((rel, ft, purpose, is_source, skip_reason))

    counts = {}
    for _, ft, _, _, _ in rows:
        counts[ft] = counts.get(ft, 0) + 1

    lines = []
    lines.append("# DataForge Scraper - File Inventory\n")
    lines.append("_Comprehensive file inventory for the DataForge Scraper repository._\n\n")
    lines.append("| file_path | file_type | purpose_guess | is_source | skip_reason |\n")
    lines.append("| --- | --- | --- | --- | --- |\n")
    for rel, ft, purpose, is_source, skip_reason in rows:
        lines.append(f"| {rel} | {ft} | {purpose} | {is_source} | {skip_reason} |\n")

    lines.append("\n## Summary by Category\n")
    lines.append("| Category | Count |\n")
    lines.append("| --- | --- |\n")
    for cat in (
        "backend_source",
        "test",
        "script",
        "config",
        "documentation",
        "docker/deployment",
        "frontend_source",
        "asset",
        "generated",
        "cache",
        "vendor",
        "binary",
        "unknown",
    ):
        if counts.get(cat, 0) > 0:
            lines.append(f"| {cat} | {counts[cat]} |\n")
    lines.append(f"| **Total** | **{len(rows)}** |\n")

    with open(OUT, "w") as f:
        f.write("".join(lines))
    print(f"Wrote {len(rows)} entries to {OUT}")


if __name__ == "__main__":
    main()
