#!/usr/bin/env python3
"""Generate lightweight code complexity reports for Prompt 6 architecture review."""

from __future__ import annotations

import ast
import json
from dataclasses import asdict, dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE_ROOTS = [REPO / "backend" / "app", REPO / "backend" / "tests", REPO / "frontend", REPO / "scripts"]
JSON_OUT = REPO / "artifacts" / "audit" / "CODE_COMPLEXITY_REPORT.json"
MD_OUT = REPO / "artifacts" / "audit" / "CODE_COMPLEXITY_REPORT.md"


@dataclass(frozen=True)
class FileMetric:
    path: str
    loc: int
    classification: str


@dataclass(frozen=True)
class SymbolMetric:
    path: str
    name: str
    kind: str
    lineno: int
    end_lineno: int
    loc: int


def classify(path: Path) -> str:
    rel = path.relative_to(REPO).as_posix()
    if rel.startswith("backend/tests/"):
        return "test"
    if rel.startswith("backend/app/routers/"):
        return "backend_router"
    if rel.startswith("backend/app/services/"):
        return "backend_service"
    if rel.startswith("backend/app/research/"):
        return "research"
    if rel.startswith("backend/app/"):
        return "backend_source"
    if rel.startswith("frontend/"):
        return "frontend_source"
    if rel.startswith("scripts/"):
        return "script"
    return "unknown"


def iter_source_files() -> list[Path]:
    files: list[Path] = []
    for root in SOURCE_ROOTS:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if (
                path.is_file()
                and path.suffix in {".py", ".js", ".mjs", ".html", ".css"}
                and "__pycache__" not in path.parts
                and "vendor" not in path.parts
            ):
                files.append(path)
    return sorted(files)


def count_loc(path: Path) -> int:
    try:
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    except OSError:
        return 0
    return sum(1 for line in lines if line.strip())


def python_symbols(path: Path) -> list[SymbolMetric]:
    if path.suffix != ".py":
        return []
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except SyntaxError:
        return []
    rel = path.relative_to(REPO).as_posix()
    symbols: list[SymbolMetric] = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            end = getattr(node, "end_lineno", node.lineno)
            kind = "class" if isinstance(node, ast.ClassDef) else "function"
            symbols.append(
                SymbolMetric(
                    path=rel,
                    name=node.name,
                    kind=kind,
                    lineno=node.lineno,
                    end_lineno=end,
                    loc=max(1, end - node.lineno + 1),
                ),
            )
    return symbols


def render_markdown(files: list[FileMetric], symbols: list[SymbolMetric]) -> str:
    largest_files = sorted(files, key=lambda item: item.loc, reverse=True)[:30]
    largest_symbols = sorted(symbols, key=lambda item: item.loc, reverse=True)[:40]
    router_files = [item for item in largest_files if item.classification == "backend_router"]
    service_files = [item for item in largest_files if item.classification == "backend_service"]

    lines = [
        "# Code Complexity Report",
        "",
        "Generated by `python3 scripts/analyze_code_complexity.py`.",
        "",
        f"- Source files scanned: {len(files)}",
        f"- Python symbols scanned: {len(symbols)}",
        "",
        "## Largest Files By Nonblank LOC",
        "",
        "| Rank | File | Class | LOC |",
        "| ---: | --- | --- | ---: |",
    ]
    for index, item in enumerate(largest_files, 1):
        lines.append(f"| {index} | `{item.path}` | {item.classification} | {item.loc} |")

    lines.extend(
        [
            "",
            "## Largest Python Functions And Classes",
            "",
            "| Rank | Symbol | Kind | File | Lines | LOC |",
            "| ---: | --- | --- | --- | --- | ---: |",
        ],
    )
    for index, item in enumerate(largest_symbols, 1):
        lines.append(f"| {index} | `{item.name}` | {item.kind} | `{item.path}` | {item.lineno}-{item.end_lineno} | {item.loc} |")

    lines.extend(
        [
            "",
            "## Router Files In Largest Set",
            "",
            "| File | LOC |",
            "| --- | ---: |",
        ],
    )
    for item in router_files:
        lines.append(f"| `{item.path}` | {item.loc} |")
    if not router_files:
        lines.append("| None in top 30 | 0 |")

    lines.extend(
        [
            "",
            "## Service Files In Largest Set",
            "",
            "| File | LOC |",
            "| --- | ---: |",
        ],
    )
    for item in service_files:
        lines.append(f"| `{item.path}` | {item.loc} |")
    if not service_files:
        lines.append("| None in top 30 | 0 |")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    paths = iter_source_files()
    files = [
        FileMetric(path=path.relative_to(REPO).as_posix(), loc=count_loc(path), classification=classify(path)) for path in paths
    ]
    symbols: list[SymbolMetric] = []
    for path in paths:
        symbols.extend(python_symbols(path))

    payload = {
        "source_file_count": len(files),
        "python_symbol_count": len(symbols),
        "largest_files": [asdict(item) for item in sorted(files, key=lambda item: item.loc, reverse=True)[:100]],
        "largest_symbols": [asdict(item) for item in sorted(symbols, key=lambda item: item.loc, reverse=True)[:100]],
    }
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    MD_OUT.write_text(render_markdown(files, symbols), encoding="utf-8")
    print(f"wrote {MD_OUT.relative_to(REPO)}")
    print(f"wrote {JSON_OUT.relative_to(REPO)}")
    print(f"files={len(files)} symbols={len(symbols)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
